### ISSUE TITLE
Documentos visitas

### ISSUE THREAD

**Issue by maperezr14** [jouribe/efronarq#26]
En el resumen de [la visita](http://54.161.81.91/visits/431) cuando se genera una cotización, se muestran los documentos de las unidades asociadas a la cotización, por ejemplo: Plano del Dpto, Plano del Estacionamiento, etc.

En algunas visitas (registradas por el cliente), algunos documentos no cargan.

![image](https://user-images.githubusercontent.com/18221255/127072101-169b7430-8a89-4680-9ad5-e068a9a186e8.png)
![image](https://user-images.githubusercontent.com/18221255/127072116-35066d52-19ef-4df9-80c9-0711ff8f139c.png)

**Comment by jouribe** [comment]
Si, porque esos documentos no existen en el backup que enviaron previamente.
